/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarefa_crud;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author thiag
 */
public class PainelLinha extends javax.swing.JPanel {

    private Pessoa pessoa;
    
    /**
     * Creates new form PainelLinha
     */
    public PainelLinha() {
        initComponents();
    }

    public PainelLinha(Pessoa pessoa) {
        initComponents();
        
        this.pessoa = pessoa;
        
        labelId.setText(Integer.toString(pessoa.getId()));
        labelNome.setText(pessoa.getNome());
        
        botaoAtualizar.addActionListener((ActionEvent e) -> {
            Conexao con = new Conexao();
            int id = pessoa.getId();
            String nome = JOptionPane.showInputDialog("Insira novo nome:");
            Boolean ret = con.atualizar(id, nome);
            if (ret) {
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível atualizar!");
            }
        });
        
        botaoExcluir.addActionListener((ActionEvent e) -> {
            Conexao con = new Conexao();
            int id = pessoa.getId();
            Boolean ret = con.excluir(id);
            if (ret) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir!");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        botaoAtualizar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        labelId.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelId.setText("id");

        labelNome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelNome.setText("nome");

        botaoAtualizar.setText("ATUALIZAR");

        botaoExcluir.setText("EXCLUIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelId)
                .addGap(51, 51, 51)
                .addComponent(labelNome)
                .addGap(90, 90, 90)
                .addComponent(botaoAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botaoExcluir)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId)
                            .addComponent(labelNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoAtualizar)
                            .addComponent(botaoExcluir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables
}
